### ISSUE TITLE
Access to EMF Toggle 

### ISSUE THREAD

**Issue by Pinheadlarry559** [VentureBlockMC/Arcadia-Survival#31]
Access to EMF toggle command to turn off fishing for custom fish.

**Comment by inkdASCENSION** [comment]
Changed a config option to only allow Special fish to be caught during competitions only.  This change will take effect after restart.

**Comment by inkdASCENSION** [comment]
Special fish will not be caught unless a fishing competition is active,.

**Comment by inkdASCENSION** [comment]
Special fish will be able to be caught at any time now, players will have access to `/emf toggle` to turn on or off special catches.
